runtime: php55
api_version: 1

handlers:
- url: /
  script: index.html

- url: /index\.html
  script: index.html

- url: /assets
  static_dir: assets

- url: /forms
  static_dir: forms

- url: /(.*\.(gif|png|jpg))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg)$

- url: /.*
  script: not_found.php
