runtime: python27
api_version: 1

handlers:
- url: /
  script: index.html

- url: /index\.html
  script: index.html

- url: /asset
  static_dir: asset

- url: /(.*\.(gif|png|jpg))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg)$

- url: /.*
  script: not_found.php
